#!/usr/bin/env python3

"""Supplementary Code 3
RNA velocity and CellRank analysis for tartary buckwheat root snRNA-seq.

Inputs
------
1. results/rna_velocity/combined_integrated_annotated.h5ad generated by script 02.
2. metadata/loom_metadata.csv listing velocyto loom files and Seurat sample suffixes.
"""

from pathlib import Path
import re

import cellrank as cr
import loompy
import matplotlib.pyplot as plt
import pandas as pd
import scanpy as sc
import scvelo as scv

PROJECT_DIR = Path.cwd()
METADATA_DIR = PROJECT_DIR / "metadata"
RESULT_DIR = PROJECT_DIR / "results"
WORKDIR = RESULT_DIR / "rna_velocity"
H5AD_FILE = WORKDIR / "combined_integrated_annotated.h5ad"
COMBINED_LOOM = WORKDIR / "combined.loom"
LOOM_METADATA = METADATA_DIR / "loom_metadata.csv"

CELLTYPE_COL = "CellAnno_Major"
GROUP_COL = "condition"
N_NEIGHBORS = 30


def combine_loom_files(loom_files, output_file):
    """Combine individual velocyto loom files into one loom file."""
    output_file = Path(output_file)
    if not output_file.exists():
        loompy.combine([str(x) for x in loom_files], str(output_file), key="Accession")
    return output_file


def harmonize_loom_barcodes(loom_adata, loom_meta):
    """Convert loom barcodes to the Seurat barcode suffix style.

    The original workflow manually rebuilt barcodes after merging loom files.
    Here the sample suffix is read from metadata/loom_metadata.csv, which makes
    the operation explicit and easier to edit.
    """
    sample_to_suffix = dict(zip(loom_meta["sample_id"], loom_meta["seurat_suffix"].astype(str)))
    new_barcodes = []
    for bc in loom_adata.obs_names:
        prefix, raw_barcode = bc.split(":", 1)
        sample_id = next((s for s in sample_to_suffix if s in prefix), None)
        suffix = sample_to_suffix.get(sample_id, "0")
        barcode = raw_barcode[:-1] + f"-1_{suffix}"
        new_barcodes.append(barcode)
    loom_adata.obs_names = new_barcodes
    loom_adata.var_names_make_unique()
    return loom_adata


WORKDIR.mkdir(parents=True, exist_ok=True)
sc.settings.figdir = str(WORKDIR)
scv.settings.figdir = str(WORKDIR)

loom_meta = pd.read_csv(LOOM_METADATA)
loom_files = [PROJECT_DIR / f for f in loom_meta["loom_file"]]
combine_loom_files(loom_files, COMBINED_LOOM)

adata = sc.read_h5ad(H5AD_FILE)
loom_data = scv.read(str(COMBINED_LOOM), cache=False)
loom_data = harmonize_loom_barcodes(loom_data, loom_meta)
adata = scv.utils.merge(adata, loom_data)

# RNA velocity analysis.
if "X_pca" not in adata.obsm:
    sc.pp.pca(adata)
sc.pp.neighbors(adata, n_neighbors=N_NEIGHBORS)
scv.pp.filter_and_normalize(adata)
scv.pp.moments(adata)
scv.tl.velocity(adata, mode="stochastic")
scv.tl.velocity_graph(adata)

scv.pl.velocity_embedding_stream(
    adata, basis="umap", color=[CELLTYPE_COL, GROUP_COL], save="_embedding_stream.pdf", title=""
)
scv.pl.velocity_embedding_grid(
    adata, basis="umap", color=CELLTYPE_COL, save="_embedding_grid.pdf", title="", scale=0.25
)

# Optional per-condition velocity plots.
if GROUP_COL in adata.obs:
    for group in adata.obs[GROUP_COL].dropna().unique():
        sub = adata[adata.obs[GROUP_COL] == group].copy()
        if sub.n_obs < 100:
            continue
        sc.pp.pca(sub)
        sc.pp.neighbors(sub, n_neighbors=N_NEIGHBORS)
        scv.pp.filter_and_normalize(sub)
        scv.pp.moments(sub)
        scv.tl.velocity(sub, mode="stochastic")
        scv.tl.velocity_graph(sub)
        safe_group = re.sub(r"[^A-Za-z0-9_]+", "_", str(group))
        scv.pl.velocity_embedding_stream(
            sub, basis="umap", color=[CELLTYPE_COL, GROUP_COL], save=f"_{safe_group}_embedding_stream.pdf", title=""
        )

# CellRank transition kernel and projection.
vk = cr.kernels.VelocityKernel(adata)
vk.compute_transition_matrix()
vk.plot_projection(basis="umap")
plt.savefig(WORKDIR / "cellrank_velocity_projection.png", dpi=300, bbox_inches="tight")
plt.close()

# Diffusion pseudotime. The root cell is selected as the cell with the largest
# third diffusion component, matching the exploratory strategy in the notes.
sc.tl.diffmap(adata)
root_ix = int(adata.obsm["X_diffmap"][:, 3].argmax())
adata.uns["iroot"] = root_ix
sc.tl.dpt(adata)
sc.pl.embedding(adata, basis="umap", color=["dpt_pseudotime"], color_map="gnuplot2", show=False)
plt.savefig(WORKDIR / "dpt_pseudotime_umap.pdf", dpi=300, bbox_inches="tight")
plt.close()

adata.write(WORKDIR / "combined_scvelo_cellrank_processed.h5ad")
